version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.6
    environment:
      CC_TEST_REPORTER_ID: $CC_TEST_REPORTER_ID
    working_directory: ~/node-bitflyer
    steps:
      - checkout

      - restore_cache:
          name: Restoring Cache - npm
          keys:
            - npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-{{ .Branch }}-

      - run:
         name: npm install
         command: npm install

      - save_cache:
          name: Saving Cache - npm
          key: npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: test
          command: |
            ./cc-test-reporter before-build
            npm test
            ./cc-test-reporter after-build -t lcov --exit-code $?
